# Generated by Django 6.0.3 on 2026-03-10 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customusermodel',
            managers=[
            ],
        ),
    ]
