# Generated by Django 6.0.3 on 2026-03-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customusermodel_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='customusermodel',
            table='users',
        ),
    ]
