# Generated by Django 6.0.3 on 2026-03-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customusermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'verbose_name': 'users', 'verbose_name_plural': 'users'},
        ),
    ]
