# Generated by Django 6.0.3 on 2026-03-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
