# Generated by Django 6.0.3 on 2026-03-14 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_item_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 3, 21, 10, 27, 54, 899926, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
