# Generated by Django 6.0.3 on 2026-03-16 11:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_item_expiration'),
        ('product', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 3, 23, 11, 5, 6, 210252, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='unique_cart_product'),
        ),
    ]
