# Generated by Django 6.0.3 on 2026-03-16 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartitem_cart_alter_cartitem_item_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 3, 23, 11, 36, 26, 659306, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
