# Generated by Django 6.0.3 on 2026-03-17 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cartitem_item_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2026, 3, 24, 17, 57, 40, 435768, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
