# Generated by Django 6.0.3 on 2026-03-17 18:14

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cartitem_item_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item_expiration',
            field=models.DateTimeField(blank=True, default=cart.models.default_expiration, null=True),
        ),
    ]
